
title: Carl Quivron
email: your-email@example.com
author:
  name: Carl Quivron
  email: carl.quivron+site@gmail.com
description: >-
  Carl Quivron | Freelance Web developer | Ruby On Rails
baseurl: ""
url: "https://carlquivron.fr"
twitter_username: carlquivron
github_username:  jjf21
date_format: "%d %b %Y"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
